version: "3.9"
    
services:
  kenstack-db:
    image: mariadb
    container_name: kenstack-db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    networks:
      kenstack_network:
        ipv4_address: 172.16.0.6
    
  kenstack-webapp:
    depends_on:
      - kenstack-db
    image: wordpress:5.8
    volumes:
      - wordpress_data:/usr/src/wordpress
      - ./wp-content/themes:/usr/src/wordpress/wp-content/themes
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ./configs/wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini 
    restart: always
    env_file:
      - ./.env
    environment:
      VIRTUAL_HOST: kenstack.io,www.kenstack.io
      WORDPRESS_DB_HOST: $DB_HOST
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_DB_NAME: $DB_NAME
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_MEMORY_LIMIT', '256M' );
        define('WP_MAX_MEMORY_LIMIT', '512M' );
        define('WP_UPLOAD_MAX_FILESIZE', '256M');
        define('WP_POST_MAX_SIZE','256M');
        define('WP_UPLOAD_MAX_SIZE','256M');
        define('CDN_URL', 'https://assets.exotravel.com/cdn-cgi/image');
    networks:
      kenstack_network:
        ipv4_address: 172.16.0.7

volumes:
  db_data: {}
  wordpress_data: {}
  wordpress_plugins: {}

networks:
    kenstack_network:
        external: true